#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("UX_OVERDIVE.Resource", IsApplication=true)]

namespace UX_OVERDIVE
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int accent = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int actionBar = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int backGround = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int text = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Clock = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Home = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int LOGO = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Microphone = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int plus = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Settings = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Sliders = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Tomato = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08001b
			public const int FL_lel = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int IpAdress = 2131230748;
			
			// aapt resource value: 0x7f080030
			public const int abort = 2131230768;
			
			// aapt resource value: 0x7f080000
			public const int button1 = 2131230720;
			
			// aapt resource value: 0x7f080015
			public const int button2 = 2131230741;
			
			// aapt resource value: 0x7f080017
			public const int button3 = 2131230743;
			
			// aapt resource value: 0x7f080019
			public const int button4 = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int button5 = 2131230746;
			
			// aapt resource value: 0x7f080020
			public const int buttonCancel = 2131230752;
			
			// aapt resource value: 0x7f08002d
			public const int buttonCancel2 = 2131230765;
			
			// aapt resource value: 0x7f08000e
			public const int buttonChangePinState = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int buttonConnect = 2131230733;
			
			// aapt resource value: 0x7f080021
			public const int buttonSave = 2131230753;
			
			// aapt resource value: 0x7f08002e
			public const int buttonSave2 = 2131230766;
			
			// aapt resource value: 0x7f08001d
			public const int editTextIPADDRESS = 2131230749;
			
			// aapt resource value: 0x7f08000b
			public const int editTextIPAddress = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int editTextIPPort = 2131230732;
			
			// aapt resource value: 0x7f08001e
			public const int editTextPORT = 2131230750;
			
			// aapt resource value: 0x7f08002f
			public const int exit = 2131230767;
			
			// aapt resource value: 0x7f080003
			public const int frameLayout1 = 2131230723;
			
			// aapt resource value: 0x7f08001f
			public const int linearLayout1 = 2131230751;
			
			// aapt resource value: 0x7f080004
			public const int relativeLayout1 = 2131230724;
			
			// aapt resource value: 0x7f080016
			public const int remote2 = 2131230742;
			
			// aapt resource value: 0x7f080018
			public const int remote3 = 2131230744;
			
			// aapt resource value: 0x7f08002b
			public const int sampleTextView = 2131230763;
			
			// aapt resource value: 0x7f080002
			public const int set_Add = 2131230722;
			
			// aapt resource value: 0x7f08002a
			public const int set_B = 2131230762;
			
			// aapt resource value: 0x7f080001
			public const int settingbutton2 = 2131230721;
			
			// aapt resource value: 0x7f080023
			public const int switch_Connect = 2131230755;
			
			// aapt resource value: 0x7f080025
			public const int switch_dv1 = 2131230757;
			
			// aapt resource value: 0x7f080027
			public const int switch_dv2 = 2131230759;
			
			// aapt resource value: 0x7f080029
			public const int switch_dv3 = 2131230761;
			
			// aapt resource value: 0x7f080022
			public const int textConnectToArduino = 2131230754;
			
			// aapt resource value: 0x7f08000f
			public const int textViewChangePinState = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int textViewChangePinStateValue = 2131230736;
			
			// aapt resource value: 0x7f080013
			public const int textViewDebug = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int textViewDebugValue = 2131230740;
			
			// aapt resource value: 0x7f080009
			public const int textViewIPAddress = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int textViewIPPort = 2131230730;
			
			// aapt resource value: 0x7f080011
			public const int textViewSensor = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int textViewSensorValue = 2131230738;
			
			// aapt resource value: 0x7f080007
			public const int textViewServer = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int textViewServerConnect = 2131230728;
			
			// aapt resource value: 0x7f080005
			public const int textViewTimerState = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int textViewTimerStateValue = 2131230726;
			
			// aapt resource value: 0x7f080024
			public const int text_dv1 = 2131230756;
			
			// aapt resource value: 0x7f080026
			public const int text_dv2 = 2131230758;
			
			// aapt resource value: 0x7f080028
			public const int text_dv3 = 2131230760;
			
			// aapt resource value: 0x7f08002c
			public const int timeDisplay = 2131230764;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Home = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int List = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Preferences = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Settings = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Sliders = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Tab = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Timed = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int TimeScript = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int menu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050014
			public const int abort = 2131034132;
			
			// aapt resource value: 0x7f050006
			public const int arduino_server_connect = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int arduino_server_text = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int button_connect_text = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int button_pin_state_text = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int change_pin_state_value = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int debug_text = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int debug_value = 2131034130;
			
			// aapt resource value: 0x7f050002
			public const int empty = 2131034114;
			
			// aapt resource value: 0x7f050013
			public const int exit = 2131034131;
			
			// aapt resource value: 0x7f050007
			public const int ip_address_text = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int ip_address_value = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int ip_port_text = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int ip_port_value = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int pin_state_text = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int sensor_text = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int sensor_value = 2131034128;
			
			// aapt resource value: 0x7f050003
			public const int timer_state_text = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int timer_state_value = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyCustomTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
